# https://circleci.com/orbs/registry/orb/circleci/docker
version: 2.1
orbs:
  docker: circleci/docker@2.1.1
workflows:
  build_and_publish_docker_image:
    jobs:
      - docker/publish:
          image: dlxmedia/docker-cypress
          tag: '9.5.4-node14.17.6-chrome100-ff98'
          extra_build_args: '--build-arg BROWSER=node14.17.6-chrome100-ff98'
          dockerfile: 9.5.4.Dockerfile
      - docker/publish:
          image: dlxmedia/docker-cypress
          tag: '10.0.3-node16.13.2-chrome100-ff98'
          extra_build_args: '--build-arg BROWSER=node16.13.2-chrome100-ff98'
          dockerfile: Dockerfile
